IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_NUMERACION_DOCUMENTOS'
)
BEGIN
    DROP PROC [dbo].[USP_NUMERACION_DOCUMENTOS];
END;
GO
/*
USP_NUMERACION_DOCUMENTOS '04','G'
*/
CREATE PROCEDURE [dbo].[USP_NUMERACION_DOCUMENTOS]
    @CODCIA CHAR(2),
    @TIPO CHAR(1)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT TOP 1
       nd.NUMERO_ACTUAL + 1 AS 'NUMERO',
       SERIE
FROM dbo.NUMERACION_DOCUMENTOS nd
WHERE nd.CODCIA = @CODCIA
      AND nd.TIPO_DOCUMENTO = @TIPO;

GO