IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_VENTAS_FILL_DET'
)
BEGIN
    DROP PROC [dbo].[USP_VENTAS_FILL_DET];
END;
GO
/*
USP_VENTAS_FILL_CAB 57339,'20240101','20241201','01'
GO
USP_VENTAS_FILL_DET 57339,'001',2727,'F','01'
SELECT * FROM dbo.CLIENTES c WHERE c.CLI_CODCLIE=57339
*/

CREATE PROCEDURE [dbo].[USP_VENTAS_FILL_DET]
    @IDCLIENTE BIGINT,
    @SERIE VARCHAR(4),
    @NUMERO BIGINT,
    @FBG CHAR(1),
    @CODCIA CHAR(2)
WITH ENCRYPTION
AS
SET NOCOUNT ON;

SELECT 
       f.FAR_CANTIDAD AS 'CANTIDAD',
       a.ART_NOMBRE AS 'PRODUCTO',
       p.PRE_PESO AS 'PESO',
       f.FAR_CANTIDAD * p.PRE_PESO AS 'PESOTOTAL'
FROM dbo.FACART f WITH (NOLOCK)
    INNER JOIN dbo.ARTI a WITH (NOLOCK)
        ON f.FAR_CODCIA = a.ART_CODCIA
           AND f.FAR_CODART = a.ART_KEY
    INNER JOIN dbo.PRECIOS p WITH (NOLOCK)
        ON a.ART_CODCIA = p.PRE_CODCIA
           AND a.ART_KEY = p.PRE_CODART
           AND p.PRE_FLAG_UNIDAD = 'A'
WHERE f.FAR_FBG = @FBG
      AND RIGHT('000' + RTRIM(LTRIM(f.FAR_NUMSER)), 3) = @SERIE
      AND f.FAR_NUMFAC = @NUMERO
      AND f.FAR_CODCIA = @CODCIA;
GO