IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_GUIA_REMISION_FILL_DET'
)
BEGIN
    DROP PROC [dbo].[USP_GUIA_REMISION_FILL_DET];
END;
GO
/*
USP_GUIA_REMISION_FILL_DET 'T001',1,'01'
GO
USP_VENTAS_FILL_DET 57339,'001',2727,'F','01'
SELECT * FROM dbo.CLIENTES c WHERE c.CLI_CODCLIE=57339
*/

CREATE PROCEDURE [dbo].[USP_GUIA_REMISION_FILL_DET]
    @SERIE VARCHAR(4),
    @NUMERO BIGINT,
    @CODCIA CHAR(2)
WITH ENCRYPTION
AS
SET NOCOUNT ON;


SELECT  grd.CANTIDAD,
       a.ART_NOMBRE AS 'PRODUCTO',
       p.PRE_PESO AS 'PESO',
       grd.CANTIDAD * p.PRE_PESO AS 'PESOTOTAL'
FROM dbo.GUIA_REMISION_DET grd
    INNER JOIN dbo.ARTI a
        ON grd.CODCIA = a.ART_CODCIA
           AND grd.IDPRODUCTO = a.ART_KEY
    INNER JOIN dbo.PRECIOS p
        ON a.ART_CODCIA = p.PRE_CODCIA
           AND a.ART_KEY = p.PRE_CODART
           AND p.PRE_FLAG_UNIDAD = 'A'
WHERE grd.CODCIA = @CODCIA
      AND grd.SERIE = @SERIE
      AND grd.NUMERO = @NUMERO;
GO