IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_MOTIVO_MODALIDAD_LIST'
)
BEGIN
    DROP PROC [dbo].[USP_MOTIVO_MODALIDAD_LIST];
END;
GO
/*
USP_MOTIVO_MODALIDAD_LIST '01'
*/
CREATE PROCEDURE [dbo].[USP_MOTIVO_MODALIDAD_LIST]
@CODCIA CHAR(2)
WITH ENCRYPTION
AS
SET NOCOUNT ON;
SELECT '-1' AS 'CODMODALIDAD', '.: SELECCIONE :.' AS 'DESMODALIDAD'
UNION
SELECT mt.Codigo AS 'CODMODALIDAD',
       mt.Descripcion AS 'DESMODALIDAD'
FROM dbo.MODALIDAD_TRANSPORTE mt
WHERE mt.Activo = 1 ORDER BY 1;

SELECT '-1' AS 'CODMOTIVO', '.: SELECCIONE :.' AS 'DESMOTIVO'
UNION
SELECT mt.Codigo AS 'CODMOTIVO',
       mt.Descripcion AS 'DESMOTIVO'
FROM dbo.MOTIVO_TRASLADO mt
WHERE mt.Activo = 1 ORDER BY 1;

SELECT '-1' AS 'CODTRANSPORTE', '.: SELECCIONE :.' AS 'NOMTRANSPORTE'
UNION
SELECT T.TRN_KEY AS 'CODTRANSPORTE',t.TRN_NOMBRE  + ' ' + coalesce(t.trn_chofer,'') AS 'NOMTRANSPORTE' FROM dbo.TRANSPORTE t
WHERE T.TRN_CODCIA= @CODCIA ORDER BY NOMTRANSPORTE;
GO